SAK-48510 Portal Search: Uncaught TypeError: e.target.querySelector(...)?.clear is not a function (#11297)
(cherry picked from commit 4fd201c92b30eb9a7286845388d32cb4104f8ec6)