SAK-48299 Portal: Edge console errors on login - Uncaught TypeError: event.getModifierState is not a function (#11190)
(cherry picked from commit 28d31786c17369841f9f1a5a9d6b63a29729b53d)