SAK-49381 T&Q: Numeric response question > Uncaught TypeError: .popover is not a function (#12046)
(cherry picked from commit 91d630cb3302fe91648db61c61291a0109b9849c)