SAK-46396: SAMIGO - Log error: "org.sakaiproject.tool.assessment.ui.servlet.delivery.ShowMediaServlet.doPost java.io.IOException: Broken pipe" (#9915)
* SAK-46396: SAMIGO - Log error: "
org.sakaiproject.tool.assessment.ui.servlet.delivery.ShowMediaServlet.doPost
java.io.IOException: Broken pipe"

* SAK-46396: Resolved issue

* SAK-46396: Refactoring

Co-authored-by: Victor <Victor@155.54.67.215>
(cherry picked from commit 150736796026a5ca456b0eb23861bef3f0d233ab)