SAK-45228 SAMLBootstrap class throws NoClassDefFoundError (#9131)
* SAK-45228 SAMLBootstrap class throws NoClassDefFoundError

* SAK-45228 add shibboleth repo for opensaml

Co-authored-by: Earle Nietzel <earle@longsight.com>
(cherry picked from commit 7349d8dd6a9c7691084c028eeb0c530fb8b8c928)