SAK-42928 - 20x, 21x Uncaught TypeError: portal.i18n.loadProperties is not a function (#7738)
(cherry picked from commit ba0f1dc85b245186643f21309d32a08ad3a7d269)