SAK-49381 Samigo numeric response question can cause js TypeError: .popover is not a function (#12059)
(cherry picked from commit 418fdd18ac0dd18cd52e101e1d31e3ee48a9bafd)